### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by JendareyTechnologies**
=================================================
Pull request for "PowerPay-MobileApp" - Web.app
=================================================

Dear Engineering Team,

I kindly request your review of the following pull request, 
which contains code changes intended for merging into our main.

Please review and approve these changes

Thank you for your collaboration.

Sincerely,

Senior DevOps Engineer
AK

### CODE REVIEW

**Review by JendareyTechnologies — COMMENTED** [review]
This looks good!! Please proceed!!!

**Review by Kenog02 — COMMENTED** [review]
This is perfect!! good to go

**Comment by finesolo2002** [comment]
Good job

**Review by djogya — COMMENTED** [review]
Looks good

**Review by emywizy — COMMENTED** [review]
looks perfect

**Review by nenycoc — COMMENTED** [review]
This looks good.

**Review by Kenog02 — APPROVED** [review]

**Comment by Metanias** [comment]
Good

**Review by finesolo2002 — APPROVED** [review]

**Comment by Eabakasampson** [comment]
good

**Review by Metanias — APPROVED** [review]

**Comment by Metanias** [comment]
Approved

**Pull request merged**
